export const genres = [
  { title: 'Action', link: '/genre/action' },
  { title: 'Adventure', link: '/genre/adventure' },
  { title: 'Avant Garde', link: '/genre/avant-garde' },
  { title: 'Boys Love', link: '/genre/boys-love' },
  { title: 'Comedy', link: '/genre/comedy' },
  { title: 'Demons', link: '/genre/demons' },
  { title: 'Drama', link: '/genre/drama' },
  { title: 'Ecchi', link: '/genre/ecchi' },
  { title: 'Fantasy', link: '/genre/fantasy' },
  { title: 'Girls Love', link: '/genre/girls-love' },
  { title: 'Gourmet', link: '/genre/gourmet' },
  { title: 'Harem', link: '/genre/harem' },
  { title: 'Horror', link: '/genre/horror' },
  { title: 'Isekai', link: '/genre/isekai' },
  { title: 'Iyashikei', link: '/genre/iyashikei' },
  { title: 'Josei', link: '/genre/josei' },
  { title: 'Kids', link: '/genre/kids' },
  { title: 'Magic', link: '/genre/magic' },
  { title: 'Mahou Shoujo', link: '/genre/mahou-shoujo' },
  { title: 'Martial Arts', link: '/genre/martial-arts' },
  { title: 'Mecha', link: '/genre/mecha' },
  { title: 'Military', link: '/genre/military' },
  { title: 'Music', link: '/genre/music' },
  { title: 'Mystery', link: '/genre/mystery' },
  { title: 'Parody', link: '/genre/parody' },
  { title: 'Psychological', link: '/genre/psychological' },
  { title: 'Reverse Harem', link: '/genre/reverse-harem' },
  { title: 'Romance', link: '/genre/romance' },
  { title: 'School', link: '/genre/school' },
  { title: 'Sci-Fi', link: '/genre/sci-fi' },
  { title: 'Seinen', link: '/genre/seinen' },
  { title: 'Shoujo', link: '/genre/shoujo' },
  { title: 'Shounen', link: '/genre/shounen' },
  { title: 'Slice of Life', link: '/genre/slice-of-life' },
  { title: 'Space', link: '/genre/space' },
  { title: 'Sports', link: '/genre/sports' },
  { title: 'Super Power', link: '/genre/super-power' },
  { title: 'Supernatural', link: '/genre/supernatural' },
  { title: 'Suspense', link: '/genre/suspense' },
  { title: 'Thriller', link: '/genre/thriller' },
  { title: 'Vampire', link: '/genre/vampire' },
]
